# Configuration file for handwriting OCR project
name: "realtime-handwriting-ocr"
version: 1.0
active: true
technologies:
- Python 3.9.18 
- TensorFlow 2.6.0
- OpenCV 4.10.0.82
- CUDA Toolkit 11.3.1
- CuDNN 8.2.1

# Training data configuration
training_data:
  batch_size: 128
  epochs: 50
  validation_split: 0.2
  callbacks_path_checkpoints: "./models/checkpoints/"
  callbacks_path_csvlogger: "./data/results/"
  callbacks_path_tensorboard: "./data/results/"
  model_save_path: "./models/save/"
  original_dataset_path: "./data/MNIST Dataset/"
  new_dataset_path: "./data/MNIST_Manual_Dataset"
  dataset_class_names: (0,1,2,3,4,5,6,7,8,9) 

# Inference configuration
inference:
  images_path: "data/inference images/"
  segmentation_threshold_value: 150
  segmentation_digit_min_area: 100
  segmentation_digit_crop_offset: 10
